version: "3.9"
# user1/password123

services:
  apache:
    image: php:8-apache
    container_name: apache
    ports:
      - "91:80"
    volumes:
      - ./apache/conf:/etc/apache2/sites-available
      - ./apache/sites:/var/www
      - ./apache/.htpasswd:/etc/apache2/.htpasswd
      - ./init/setup_apache.sh:/docker-entrypoint-init.d/setup_apache.sh
    command: ["/bin/bash", "/docker-entrypoint-init.d/setup_apache.sh"]
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "90:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/sites:/var/www
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./init/setup_nginx.sh:/docker-entrypoint-init.d/setup_nginx.sh
    command: ["/bin/bash", "/docker-entrypoint-init.d/setup_nginx.sh"]
    restart: unless-stopped
