version: "3.9"

services:
  apache:
    image: php:8-apache
    container_name: apache
    ports:
      - "91:80"
      - "444:443"
    volumes:
      - ./apache/conf:/etc/apache2/sites-available
      - ./apache/sites:/var/www
      - ./apache/.htpasswd:/etc/apache2/.htpasswd
      - ./apache/ssl:/etc/ssl
      - ./apache/cache:/var/cache/apache2
      - ./init:/docker-entrypoint-init.d
    command: ["/bin/bash", "/docker-entrypoint-init.d/setup_apache.sh"]
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "90:80"
      - "446:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/sites:/var/www
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/ssl:/etc/ssl
      - ./nginx/cache:/var/cache/nginx
      - ./init:/docker-entrypoint-init.d
    command: ["/bin/bash", "/docker-entrypoint-init.d/setup_nginx.sh"]
    restart: unless-stopped
